# Generated by Django 3.2.9 on 2022-05-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_umkm',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_umkm',
            name='daftar_produk',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_umkm',
            name='foto_kedai',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='data_umkm',
            name='foto_produk',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='data_umkm',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='data_umkm',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='data_umkm',
            name='nama_pemilik',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
