# Generated by Django 3.2.9 on 2022-04-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20220419_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='topik',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='topik',
            name='gambar',
            field=models.ImageField(upload_to='static/forum/%Y/%m/%d'),
        ),
    ]
