# Generated by Django 3.2.9 on 2022-05-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='berita',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('tanggal', models.DateField()),
                ('penulis', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('gambar', models.ImageField(upload_to='static/berita/%Y/%m/%d')),
                ('isi_berita', models.TextField()),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
